# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0004_auto_20170104_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opravilo',
            name='podrocje',
            field=models.CharField(choices=[(1, 'Šola'), (2, 'Delo'), (3, 'Dom'), (4, 'Nakupovanje'), (5, 'Ostalo')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='opravilo',
            name='prioriteta',
            field=models.CharField(choices=[(1, 'Najmanj pomembno'), (2, 'Pomembno'), (3, 'Zelo pomembno')], default=1, max_length=50),
        ),
    ]
