# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0009_auto_20170106_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='uporabnik',
            name='mail',
            field=models.CharField(default='sth@gmail.com', max_length=30),
        ),
    ]
