# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0011_auto_20170106_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opravilo',
            name='prioriteta',
            field=models.CharField(choices=[('Najmanj pomembno', 'Najmanj pomembno'), ('Pomembno', 'Pomembno'), ('Zelo pomembno', 'Zelo pomembno')], default=1, max_length=1),
        ),
    ]
