# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0015_auto_20170106_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opravilo',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='opravilo',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='opravilo',
            name='podrocje',
            field=models.CharField(choices=[('1', 'Šola'), ('2', 'Delo'), ('3', 'Dom'), ('4', 'Nakupovanje'), ('5', 'Prosti čas'), ('6', 'Ostalo')], default=1, max_length=1),
        ),
    ]
