# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0017_auto_20170108_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opravilo',
            name='createDate',
        ),
        migrations.AlterField(
            model_name='opravilo',
            name='uporabnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
