# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0018_auto_20170109_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opravilo',
            name='zapiski',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
